describe('versioning', () => {
  it.todo('summarize the changes in the new version vs old')
  it.todo('be aware of what version we are currently running')
  it.todo('bots should put out a version too')
  it.todo('modified bot should show its base plus modified symbol')
  it.todo('self bot should describe the syntax used in the versions+')
  it.todo('read release notes and provide a summary of changes')
  it.todo('release notes summary for a range of versions')
  it.todo('detect a new version available on github')
})
